#define PATCH_EXPRESSION

#ifdef PATCH_EXPRESSION
#define USE_MPE
#endif

#if VOICES == 1
#define GAINFACTOR 1
#elif VOICES == 2
#define GAINFACTOR 0.70
#elif VOICES <= 4
#define GAINFACTOR 0.5
#elif VOICES <= 6
#define GAINFACTOR 0.4
#elif VOICES <= 8
#define GAINFACTOR 0.35
#else
#define GAINFACTOR 0.25
#endif

#define BUTTON_VELOCITY 100

#define PARAMETER_FX_AMOUNT               PARAMETER_E
#define PARAMETER_WAVESHAPE               PARAMETER_H // FX Amount for QuadSampler, Stereo Mix for WaveBank
#define PARAMETER_STEREO_MIX              PARAMETER_H
#define PARAMETER_ATTACK                  PARAMETER_AA
#define PARAMETER_DECAY                   PARAMETER_AB
#define PARAMETER_SUSTAIN                 PARAMETER_AC
#define PARAMETER_RELEASE                 PARAMETER_AD
#define PARAMETER_ATTACK_CURVE            PARAMETER_AE
#define PARAMETER_RELEASE_CURVE           PARAMETER_AF

#define PARAMETER_EXTL_AMOUNT             PARAMETER_AG
#define PARAMETER_EXTR_AMOUNT             PARAMETER_AH

#define PATCH_PARAMETER_ATTENUATE_A PATCH_PARAMETER_BA
#define PATCH_PARAMETER_ATTENUATE_B PATCH_PARAMETER_BB
#define PATCH_PARAMETER_ATTENUATE_C PATCH_PARAMETER_BC
#define PATCH_PARAMETER_ATTENUATE_D PATCH_PARAMETER_BD

#define PATCH_PARAMETER_LFO1_SHAPE  PATCH_PARAMETER_BE
#define PATCH_PARAMETER_LFO2_SHAPE  PATCH_PARAMETER_BF

#define PARAMETER_FX_SELECT         PATCH_PARAMETER_BG

#define PARAMETER_DYNAMIC_RANGE     PATCH_PARAMETER_BH

#define PATCH_PARAMETER_MODULATION_AMOUNT RPN
#define PATCH_PARAMETER_PRESSURE_AMOUNT

#define FX_PHASER                                   15
#define FX_DELAY                                    47
#define FX_OVERDRIVE                                79
#define FX_CHORUS                                  111
